name: Dotfiles CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  check-install.sh:
    name: Test install.sh
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check shell script syntax
        run: bash -n ./install.sh

      - name: Make script executable
        run: chmod +x ./install.sh

      - name: Execute install.sh
        run: ./install.sh
